import 'package:flutter/material.dart';
import 'package:android_intent_plus/android_intent.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'تست پرینتر',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const Directionality(
        // add this
        textDirection: TextDirection.rtl, // set this property
        child: MyHomePage(title: 'تست پرینتر'),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _print() async {
    String image =
        "iVBORw0KGgoAAAANSUhEUgAABNQAAAJhCAYAAACJn+11AAAACXBIWXMAACE4AAAhOAFFljFgAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAB4HSURBVHgB7d0tiF1nHsfxp91SE1UTVTOqJmpNVM2oNYGVgYU1Aws1gUJNINAVhahSiCqF8aNKYVRNVM2omlE1o2pG1Yyq6OY/5Wynk0l6fzPPueflfj5wSbcs6b3nnuec83zveXnnt1caAAAAALCRdxsAAAAAsDFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACgho0AAAAgM0JagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAwHsNgI0cHh62i4uLNmcPHjxo+/v7bU7Ozs7a8fFx62Vvb689evSoAQDLdXR01M7Pz9ucOeYA3kZQA9jQycnJ7A/8ytyCWkXIly9ftl4qGjq4BYBlOz09vXzNmWMO4G1c8gkAAAAAAUENAAAAAAKCGgAAAAAE3EMNAADaMu7pVB4/ftwAgGkJagAA0H4PavXkwbkT1ABgei75BAAAAICAoAYAAAAAAUENAAAAAAKCGgAAAAAEBDUAAAAACAhqAAAAABAQ1AAAAAAgIKgBAAAAQEBQAwAAAICAoAYAAAAAgXd+e6UB8JfOz8/b3N27d+/yNTe9l939+/cbQG9HR0eXr7n77rvvGizdxcXF5WvuHHMAb/JeA2AjDqhuz7IDAK6a64+AAJtyyScAAAAABAQ1AAAAAAgIagAAAAAQ8FACAABovz9AZQkPoHnw4EEDAKYlqAEAAABAwCWfAAAAABAQ1AAAAAAgIKgBAAAAQEBQAwAAAICAoAYAAAAAAUENAAAAAAKCGgAAAAAEBDUAAAAACLzXACZ0dHTUzs/P213du3evHRwctKU6PDxsFxcX7a7mvBzq89Xn7OHhw4eXr7Vb4vjo9Z7LkydP2pr1Gvd7e3vt0aNHbS16bisePHjQ9vf32y47Oztrx8fHrYdalrVM52DOn+v09LS9fPmy9dDzva35WOPk5OTy1cPjx4/b/fv3G8BfEdSASdVBZ73uqg58lhzU6iCwR4SY83Kog/heE4z6nLsQ1JY4Pnq957L2oNZr3Ndke21Brde2oux6UOu5POcS08qcP1eN6zm+tzUfa1Rg7RkxBTVgEy75BAAAAICAoAYAAAAAAUENAAAAAAKCGgAAAAAEBDUAAAAACAhqAAAAABAQ1AAAAAAgIKgBAAAAQEBQAwAAAICAoAYAAAAAAUENAAAAAAKCGgAAAAAEBDUAAAAACAhqAAAAABAQ1AAAAAAgIKgBAAAAQEBQAwAAAICAoAYAAAAAAUENAAAAAAKCGgAAAAAEBDUAAAAACAhqwCpcXFw0ALjKvmG9fLcATE1QA1ahDqyXfHDd673PeRn0fG8mUrth7d+z9Xh8Z2dnjX7mtM6en5+3XnqvJz3f2xz3nbZdAL8T1IDV6HkAu009Y+Ccw2LP97XU7zq16zFgzZ9/6T8CjOn+/futl9pW7Ppy7jmO5rTtPT09bb303tb0/Pt6/V3196z5WMP2FJiCoAasRs+D622a84F8TycnJ62XpX7XCSFg3d+zM6e25+XLl22XzTHu3FVtH3vuU3rGpt7vrdff1fu76/kZe+i5v+gZ9YF1E9SA1Zjbwd2mek/25jp57Pn91MRn7VHt6Oio9bLUycHx8XFbq57j9N69e21ten6mpe4beqi403Ndq+3uHM5S671tqH1Kr7+z57a71Hvr8R32fl9zOtao9dKPFMAUBDVgNeqAamkT8DoAHCOoze3Asg7ke0/Cek8O5qT3JHipek5y56S+257f7xrPpugZ1Ja4b+hljO3k4eFhm1KNnTG+z1pWd9131vsaY9tdy/wu+9Ax9sE1rubww1btJ168eNF6coYasClBDViVOmhcSoioA/fnz5+3MdTfO5d73dR3Msakrg7kex9Ez0GtF8+ePWs97e3ttaWqieSaYkitt72DxBrPUOu9zq5tPdpEfeYx9od1xt9UP2jUdzjmdr+2vbddZrVMxoqNFY3qvd1mvz7WPrjUscaUP+DdZbm8yRq3p8B4/vbfVxrAROrAteeB0K+//np5sF9/Zx0UzfFXxjoA/Pbbb9uXX3452j2yhktEannUMpjiAHEIXmMGzuEMv/p8S45GZcz14uOPP24fffRR24beY7r8+OOPl9/1Bx98sNgzB+r91/f79ddfX47Lnh49etQ+/PDDtiY//fTT5aunWo9qu1Tbi7Utr6vqM1boGPNS1/pv1N9fy3HsMVnbw1oXan/y/ffftzENxxA1Xt9///2/XE/qvf3www+jxcvr/60KirV9rf3d2/brV5fZmO+rltfwnWzzWKM+X/136/P9/PPPrafaV+7v7zeATbzz2ysNYCL1y+KYlwwMoWWIa1P98jg8EasO0qf4NffBgwdbWQbDjfTrO932DfWH77o+41Kiy7bWiy+++OJyHdiGscd02db6fFfD9zv2fae++uqrxQfl6yoCjHkm0tXtRf3z0s9KmXLbO2xze257h/FS28WpH9ByfXtz9b1NeXZWvZ+rxzdX9ydTLbOr++AxxlR9rnr1fIjEdfUDxcHBQQPYxHsNYMV24eb1m9iFZeC7frO1xRbf8x+GSfXajP2ZbC/6GSLHWs11PZnjcp86MvawrR+fgHVwDzUAWLHh7ArWaY0xrfzVJW0AY1jrNhUYh6AGACv28OHDxnqt+fu17gLbNFyyCrApQQ0AVkyUWLc1f79uDA5sU90/DSAhqAHAStXlnn5tX68KTmu+LNJln8A2uX8akBLUAGClnOGzbo8fP25rVjHNGSPANtT+0g9QQEpQA4AVqomBoLZeuzL5q6DmLDVgbGv/gQIYh6AGACv09OnTxnrtyuTPWWrA2Gp76uw04DYENQBYmQoQdf8p1mnXJn+1PpvsAmOobYuz04DbEtQAYEVMDtatnuq5a99vnaX25MmTBtDbF1980QBuS1ADgJWomFaTA/ecWqf6fg8ODtouqqfv7epnB8ZR2xRnvwJ3IagBwApURKuYZnKwTkMs3eXvty79dPYlibnef89DY6ZX2xL3ZwTuSlADWIA6+N6Fm8zXBMMBbk5sWTff7x9qEiyq9VfLdG2Bpy4TrjOQ6jLpORl+/Jjj2VG1HsxteY3BdgToRVADmLk6+K6YVge5a77kqW6iX5+vXnV5F5up5VaTMw8hWKcaC1999ZWYdoXJcF8V0mp5runyt/osQyCssDaX7ePVM4nndlbxsB7U8lrr9mY4nrL9AHr5239faQATefnyZTs/P2/cbDjgHiYDH3300eWfp6enbU0qGnz++ef/v/dXxcMff/yx/fLLL403q7P5avLzwQcftLkwpvuosfDvf/+7ffLJJ+39999v/FltMyoAnJyctIuLi8bt1DIcHvhQ61lte5e8TGvc1L7k448//v+/q89V/7v2J2dnZ20qFanqvV2Ne/V+57DMa19S25qyhvXgJsNxxnAcBdCDoAZMyuT7zYaDvw8//PC1f18H4T/99FP79ddf29LVgfxnn332p2hQ//yPf/zj8p/XFg97qHWgJsG1jOYWW4zpuxvG/t///vfGm9V2cLhEvNY5YW1zQ7Ct1/V/X5Ft6vh0G8O4uelstCESTbXvrP92vbebzvwalnm9p3pv2zSsB9fP2BpCX42ppa0H1w0Pc6mXB/YAvb3z2ysNYCL/+c9/uky+hxv8Hh0dtaWrA75NbpZby60+bwWMJRqe2vdXl+LUwfzh4aGw1n5fZrVuzPmS2E8//bTLBGwYB/Xd74qawNa4d8lzrraHtY2obaKg+3bD7QP+6rK+2rcsYXmm28Vt7jtv895evHixlf1dHTNtEpmWsh5cV8cW9RnrJaQBYxHUgEn985//bD3UgVPdZ2ipkakO9uoz1GQ6vSHw8JnrAHzuB7zDL/H1GdNoUJ+vvtclfM6eajnV8lrKpOBf//pXlzOFarL/zTffLD4cv80w7pf0/S7BsK2osLv0s2t6GX50qld6f6y69G94zeUswPoMNW5usy8ZDBF22K/0cpf93NX3dnx8fPm+eq7D9X7qVcca6famllOtA/We5no2aI/1AiAhqAGTqYPEOpulhzpwqnuNDYYD5SG+DK+p1QFsveqgr141mR5ePSbTwwRyeNVBb722/dmHCVt9ruFz1nfU60bHwySjPtfw5/BZl2hYLmOtF9tSy7+CWg9vGtPDuj2XMb2Jq+NhiGhL/H6XaNhG3LRNXOMlosPN7q9uS8bY9g5RZext79if56qr+5Xhc73t8920nxtePV1dh6++tzft22/an9Sfw+0ieri+Dx7e5zb2w8Nx1LAtHf4ca70AeBtBDZhM/dL5/Pnz1kP9GllPbgKmU5OsZ8+etR6uBzUAAJiTdxvARHpeYtH7F2EgZ0wDALArBDVgMj0n307zh+kZ0wAA7ApBDZjE1ftu9GDyDdMa7nHWizPUAACYM0ENmEQ9ta8nk2+YljENAMAuEdSAraszWerx6714Uh5Ma4yz04xpAADmTFADtq73mSz1NEBgOhXIK6r14uw0AADmTlADtqrum9bz7LQiqMF0KqSJ5AAA7BpBDdiamng/f/689WbyDdOoMf3s2bPWmzENAMDcCWrAVlxcXFzGtJ6XhZWHDx+61xJMYKwxXTHNU3sBAJi79xrAyIYz0+pyz94qqAHbVTGtzkwbY0zv7+83AACYO0ENGFVNuMc4i6XUWSwm37Bdw2WeY4zpOttUJAcAYAkENWAUdQbL8fFx95uVX+U+S7A9w5iuV/3zGFzCDQDAUghqQFfbmHQPHj9+3IBxDWO6ns47xllpVxnTAAAshaAG3FlNsk9PTy9fJycno4e0Upd6unE5jKPGcI1lYxoAAG4mqAF/Mkyk32Q4Q6X+rP9v3SNt7LNWbuJMFm6r1tnDw8M2dwcHB21vb6/1UGeXvcnaxvSLFy8mef+JulzdNgwAYNkENeBP6v5FNSGds0ePHjmThVuraFRnXs1dz7PCKiBu4yyz2+p5dlp9t3MParZfAADL924DuGbONwWviWgFNWBzcx/TztYCAGBpBDXgNXOefNfE29kdkDGmAQCgL0ENeM1cJ7d1WVi9gMxcx3TdS8yYBgBgiQQ14DVznHy7LAxub45nqNWYfvLkSQMAgCUS1IBFePr0qcvC4JbmGNQqphnTAAAslaAGvGZuk9yDg4O2t7fXgNuZW1Crs03rck8AAFgqQQ14zZwm3zXx9lRPuJs5RfIa0y7fBgBg6QQ14DVzCWom3tCHMQ0AAH291wCumcPZLHWZpzPToI85jGkxDQCANRHUgNdMeTZL/bfrAQTurwT9TD2mK5Dv7+83AABYC0ENeM1Uk+968ICneUJ/xjQAAPQlqAGvmWLy63IwGM8UQa0u2a4xPbcnjAIAQA+CGnCjmgRfXFy0sdWlnXU5WJ3JAoynQvn5+XkbW43pCmku2wYAYM0ENeBGYwe1CmgV0ky6YTvGPlOsgl2N6YcPHzYAAFg7QQ240Vhnszh7BaZRY/rs7Kz1VmO5HjjgoQMAAOwSQQ24Uc+zWervqsl2nbkipDG1Wge/++67tmt2ZUx/8803DQAAxiaoATe66+S7LumsibaIBvNw1zFdZ7jVeK5XjW8PGwAAYJcJasCNNnnSZ02o61X/33rVJHt4mWzDvGw6JofxPIzp+rOiuDENAAB/eOe3VxrANfVAgrc9lGCT4AbMhzENAAD9CGoAAAAAEHi3AQAAAAAbE9QAAAAAIOChBADAzjo+Pr583cXTp08vH+AAAMDuENQAgJ1VD2o4Pz9vd/G2hz0AALBOLvkEAAAAgICgBgAAAAABQQ0AAAAAAoIaAAAAAAQENQAAAAAICGoAAAAAEBDUAAAAACAgqAEAAABAQFADAAAAgICgBgAAAAABQQ0AAAAAAoIaAAAAAAQENQAAAAAICGoAAAAAEHjnt1caAMAOuri4uHzdxb179y5fAADsDkENAAAAAAIu+QQAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAgIagAAAAAQENQAAAAAICCoAQAAAEBAUAMAAACAgKAGAAAAAAFBDQAAAAACghoAAAAABAQ1AAAAAAj8D6J37G9ncNFZAAAAAElFTkSuQmCC";

    var intent = AndroidIntent(
      action: 'action_view',
      arguments: {'image': image},
      data: Uri.encodeFull('netbee://plugin.printer.netbee.online/'),
      type: "text/plain",
    );
    await intent.launch();
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        child: OutlinedButton(
          style: ButtonStyle(
            shape: MaterialStateProperty.all(RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(10.0))),
          ),
          onPressed: _print,
          child: const Text('چاپ'),
        ),
      ),
    );
  }
}
